# Generated by Django 4.2.7 on 2023-12-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='Not available', max_length=100)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
